---

# roles/postgresql/tasks/main.yml

- name: Install postgresql
  include: install.yml
  when: action == "install"
  tags: ['install']

- name: Start postgresql
  include: start.yml
  when: action == "start"
  tags: ['start']

- name: Stop postgresql
  include: stop.yml
  when: action == "stop"
  tags: ['stop']

- name: Restart postgresql
  include: restart.yml
  when: action == "restart"
  tags: ['restart']

- name: Enable postgresql
  include: enable.yml
  when: action == "enable"
  tags: ['enable']

- name: Disable postgresql
  include: disable.yml
  when: action == "disable"
  tags: ['disable']

- name: add remote user to postgresql
  include: add_remote_user.yml
  when: action == "add_remote_user"
  tags: ['add_remote_user']