---
- name: Creating host groups from dynamic inventory
  hosts: localhost
  connection: local
  tags: ['info', 'install', 'start', 'stop', 'uninstall', 'ssh']
  vars:
    zookeeper_tag_original: "{{ zookeeper_tag | default('') }}"
    zookeeper_tag_name: "tag_{{ zookeeper_tag_original | replace('-', '_') }}"
    hadoop_tag_original: "{{ hadoop_tag | default('') }}"
    hadoop_tag_name: "tag_{{ hadoop_tag_original | replace('-', '_') }}"
    namenode_tag_original: "{{ namenode_tag | default('') }}"
    namenode_tag_name: "tag_{{ namenode_tag_original | replace('-', '_') }}"
    datanode_tag_original: "{{ datanode_tag | default('') }}"
    datanode_tag_name: "tag_{{ datanode_tag_original | replace('-', '_') }}"
  tasks:
    - add_host: name={{ item }} groups=zookeeper
      with_items: "{{ groups[zookeeper_tag_name] }}"
      when:
        zookeeper_tag_name | trim != "tag_"

    - add_host: name={{ item }} groups=hadoop
      with_items: "{{ groups[hadoop_tag_name] }}"
      when: 
        hadoop_tag_name | trim != "tag_"

    - add_host: name={{ item }} groups=namenode
      with_items: "{{ groups[namenode_tag_name] }}"
      when: 
        namenode_tag_name | trim != "tag_"

    - add_host: name={{ item }} groups=datanode
      with_items: "{{ groups[datanode_tag_name] }}"
      when: 
        datanode_tag_name | trim != "tag_" 


- name: Execute Hadoop roles
  hosts: hadoop
  user: centos
  become: true
  become_method: sudo
  become_user: root
  roles:
    - role: hadoop
