---

# roles/vpc/tasks/main.yml
- name: Fail play if the action name is not defined
  fail: 
    msg: "Specify the action name: -e 'action=launch'"
  when: action is undefined
  tags: ["launch", "terminate"]

- name: Launch VPC instances
  include: launch.yml
  when: action == "launch"
  tags: ["launch"]

- name: Terminate VPC instances
  include: terminate.yml
  when: action == "terminate"
  tags: ["terminate"]