---
- name: Fail play if the cluster tag Name is not defined
  fail:
    msg: "Specify 'Name' for the cluster in tag_key_vals variable"
  when: tag_key_vals.Name is undefined
  tags: ["launch"]

- name: Fail play if the action name is not defined
  fail: 
    msg: "Specify the action name: -e 'action=launch'"
  when: action is undefined
  tags: ["keypair", "launch", "start", "stop", terminate", "describe"]

- name: Create KeyPair
  include: keypair.yml
  when: action == "keypair"
  tags: ['keypair']

- name: Launch EC2 instances
  include: launch.yml
  when: action == "launch"
  tags: ['launch']

- name: Start stopped EC2 instances
  include: start.yml
  when: action == "start"
  tags: ['start']

- name: Stop EC2 instances
  include: stop.yml
  when: action == "stop"
  tags: ['stop']

- name: Terminate EC2 instances
  include: terminate.yml
  when: action == "terminate"
  tags: ['terminate']

- name: Describe EC2 instances info
  include: describe.yml
  when: action == "describe"
  tags: ['describe']